### ISSUE TITLE
[hi] `Kubernetes` for `Hindi`

### ISSUE THREAD

**Issue by devsachinsharma** [cncf/glossary#1013]
#### What this term is about? (briefly)
- It is a container orchestrator engine. It helps in deploying and managing containerized applications.
#### Why this term needs to be added? (briefly) 
- This term needs to be added because it manages containers and also self repairs them. So it is a very important term.
#### Languages that use this term? (briefly)
- English and Hindi

**Comment by devsachinsharma** [comment]
Can I be assigned to this term?

**Comment by pratik2315** [comment]
Hey there @devsachinsharma! I am kinda new here, just trying to understand this community. I had a question for you😅
If I am correct this issue is targeted to provide an Hindi translation for the [this](https://glossary.cncf.io/kubernetes/) "Kubernetes" section in the glossary website. 
Will you then be working upon the translating the whole section or just some bits of it?🤔

**Comment by devsachinsharma** [comment]
@pratik2315 the whole section.

**Comment by devsachinsharma** [comment]
@anubha-v-ardhan  @jayesh-srivastava  @Garima-Negi  @sayantani11  can someone please assign me to this topic.

**Comment by Garima-Negi** [comment]
old issue. new issue has been created for kubernetes.md
