### ISSUE TITLE
[hi] Localize `Version Control` for `Hindi`

### ISSUE THREAD

**Issue by bishal7679** [cncf/glossary#1036]
#### What this term is about? (briefly)
-  Source control (or version control) is the practice of tracking and managing changes to a document. It is a system that records changes to a file or set of files over time so that you can recall specific versions later.

#### Why this term needs to be added? (briefly) 
- Localizing this term in hindi will help hindi folks to learn about this term in their native language

**Comment by jihoon-seo** [comment]
Hello @bishal7679 
I think it would be great if one of Hindi L10n team approvers (@Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava) assign you (or someone else) for working on Hindi L10n jobs.

**Comment by bishal7679** [comment]
Yes Please Can anyone assign me
@Garima-Negi @anubha-v-ardhan @sayantani11 @jayesh-srivastava

**Comment by anubha-v-ardhan** [comment]
Thankyou @bishal7679 :)

**Comment by bishal7679** [comment]
@anubha-v-ardhan @jihoon-seo Can you tell me what is happening here
When I am making a PR from my branch `hi-version-control` to `dev-hi` it is taking all the commits of everyone in my PR that made before.
please help me out
![Screenshot (170)](https://user-images.githubusercontent.com/70086051/177389317-e03e1d18-31e3-44d1-9f49-a13635eb88e0.png)

**Comment by anubha-v-ardhan** [comment]
@bishal7679 I believe the branch `hi-version-control` on your fork is branched from `main` which is causing this issue. Since `dev-hi` is not on par with `main`, `hi-version-control` carries all the changes on `main` when you make a PR from `hi-version-control` to `main`.

The best solution in my opinion is to make the working branch on your fork from `dev-hi`. As a general rule, always make your working branch from the branch where your PR will merge in future.

If you don't want to start all over again, you can fix this using a rebase too!
