### ISSUE TITLE
The custom search uses old indexes

### ISSUE THREAD

**Issue by musaprg** [cncf/glossary#1052]
Hi, I found that several search index data were old and didn't reflect the actual path format. ref) https://github.com/cncf/glossary/pull/922

For example, currently `Shift Left` page is on `/shift-left`, but the search result links to `/shift_left`.

**Comment by jihoon-seo** [comment]
@musaprg Thank you for filing this issue!

It seems that this is because Google Search cache is not up-to-date for some pages of CNCF Glossary website.

For me for now, 
when visiting https://glossary.cncf.io/search/?q=Shift%20Left ,
![image](https://user-images.githubusercontent.com/46767780/178173097-de8e7d35-b714-4aca-bb82-15f49838519e.png)

- Up-to-date indexes
  - https://glossary.cncf.io/shift-left/
  - https://glossary.cncf.io/tightly-coupled-architectures/
  - https://glossary.cncf.io/auto-scaling/
  - https://glossary.cncf.io/continuous-integration/
  - https://glossary.cncf.io/version-control/
  - ...
- Outdated indexes
  - https://glossary.cncf.io/stateless_apps/
  - https://glossary.cncf.io/vertical_scaling/
  - https://glossary.cncf.io/self_healing/
  - ...

@cjyabraham what do you think about this? 😊
Might we just wait then Google Search cache will be updated someday,
or would it be great to somehow trigger to update the Google Search cache? 🤔

**Comment by cjyabraham** [comment]
I can submit urls for "priority indexing" through Google Search Console, however, there's a daily quota of urls I can submit, which I've now hit. I have, however, just submitted [the sitemap](https://glossary.cncf.io/sitemap.xml) to GSC so that should also have an effect. 

Note [this recent change I made](https://github.com/cncf/glossary/commit/1d6e12a2a9e7f9c8b1b7381f0646043b96336c14) broke the sitemap so [I have reverted it](https://github.com/cncf/glossary/commit/801443f1ac4fbc3a506dbebc092036a8404b7dfd).

**Comment by cjyabraham** [comment]
I can't find any searches that still produce wrong urls so will close this issue. If you find any more please reopen.
