### ISSUE TITLE
How To Contribute More

### ISSUE THREAD

**Issue by prasadjivane** [cncf/glossary#1108]
I would like to contribute more to the community.
Add me to the community.

**Comment by NitishKumar06** [comment]
@prasadjivane Get your invite to CNCF-slack channel here: https://communityinviter.com/apps/cloud-native/cncf

Once done, Find a channel in slack: glossary.

Congratulations, You've joined the community!

**Comment by seokho-son** [comment]
Hi @prasadjivane 
Thank you for your interest ! Welcome :)

I am a maintainer of this Glossary repository. 
You can find a guide document to initiate your contribution.
So, PTAL :)
- https://glossary.cncf.io/contribute/
- https://glossary.cncf.io/style-guide/
- https://glossary.cncf.io/contributor-ladder/

and since this Issue is a simple and general question, let me close this Issue.
You can utilize #glossary Slack channel for some general questions next time.
