### ISSUE TITLE
Initiate Urdu Localization Team

### ISSUE THREAD

**Issue by waleed318** [cncf/glossary#1310]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

For example, the two-letter code for Korean is `kr`.

 - Language name (ex: `Urdu`): 
 - Language two-letter code (ex: `ur`): 

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

Ex: `- [A] Seokho Son (@seokho-son)`

- [A] Saim Safdar (@Saim-Safdar)
- [A] Waleed Ahmed (@waleed318)
- Ali Raza (@Ali15700)
- Fateh Muhammad (@FatehMuhammad)
- Haseeb Shaukat (@mhaseebshaukat)

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-kr`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by Saim-Safdar** [comment]
Thank you, Waleed, now we just need to create the dev branch but wouldn't be able to do so because we don't have permission, can you please help us with that @CathPag

**Comment by CathPag** [comment]
Awesome, @seokho-son and @jihoon-seo will walk you through the process :)

**Comment by waleed318** [comment]
Hi @seokho-son and @jihoon-seo, Need to create local branch for Urdu (dev-ur) as soon as possible. Guide us through the process, so we can start working.

**Comment by seokho-son** [comment]
Hi @waleed318 

- label for ur: https://github.com/cncf/glossary/labels/lang%2Fur
- `#glossary-localization-urdu` channel in CNCF Slack (please invite all ur team members to the channel) 

By the way, I think one approver is not enough considering an approver cannot approve his/her PR by self. 
Also, in order to merge a PR to dev-ur, the PR requires at least two approvals (from two approvers except author of the PR).

- [A] Saim Safdar (@Saim-Safdar)
- Waleed Ahmed (@waleed318)
- Ali Raza (@Ali15700)
- Fateh Muhammad (@FatehMuhammad)

Please discuss with your team members who can participate as additional approver. 
Candidates may need to check #723 in advance. (If there is no eligible approver, please consult with maintainers) 

In the meantime I will create dev-ur for Urdu team ! Thanks~!

**Comment by waleed318** [comment]
### Team
-  [A] Saim Safdar (@Saim-Safdar)
-  [A] Waleed Ahmed (@waleed318)
-  Ali Raza (@Ali15700)
-  Fateh Muhammad (@FatehMuhammad)
- Haseeb Shaukat (@mhaseebshaukat)

**Comment by seokho-son** [comment]
Ok, I assume your comment suggests that Urdu team will initiate with two approvers. :)

**Comment by seokho-son** [comment]
https://github.com/cncf/glossary/tree/dev-ur 🎊

**Comment by jihoon-seo** [comment]
I guess that we should update `dev-ur` branch with the latest `main` branch, to make #1324 effective in `dev-ur` branch too. 😊

**Comment by seokho-son** [comment]
Yes @jihoon-seo 

Cloud you open ?

**Comment by seokho-son** [comment]
I think tasks to initiate Urdu team are complete !
