### ISSUE TITLE
Plan for Localization

### ISSUE THREAD

**Issue by JasonMorgan** [cncf/glossary#159]
Make a plan and add suggestions for how we can handle localization of the glossary.

**Comment by sayantani11** [comment]
SUGGESTION/ PLANNING FOR LOCALIZATION OF GLOSSARY:
1. The localization should be under one folder like for example : `./content/en` for English, `./content/hi` for Hindi, `./content/ko` for Korean.
2. For every localization there should have a maintainer who will look after all the changes being made.
3. The PRs for localization should start with `[hi] Vertical Scaling` which makes it easy to understand that it is the Hindi Localization of Vertical Scaling.
4.  The localization should have one particular issue for example : `[hi] Hindi Localization of glossary`.
5. The issue should have a checklist of task that needs to be done for the localization and the reviewers or maintainers should make sure they check the task after a PR has been merged.
6. New tags should be introduced which for localization PRs, for example: `/language [xy]`.
7.  The word `localization` should be used instead of `translation`
8. A readme maintained for every localization which shows the name of the contributor along with the localization done.
    For example:  `Vertical Scaling ~ @sayantani11`
9. There should be a slack channel for every localization where contributors could discuss if they have doubt with something.

**Comment by sayantani11** [comment]
@JasonMorgan I would like to work on localization in Hindi if you allow😊

**Comment by edsoncelio** [comment]
Hey @JasonMorgan, if possible, i want to know more about the localization (to be more specific i want to work on localization in portuguese) :D

**Comment by CathPag** [comment]
Hi @sayantani11 @edsoncelio, so so sorry for the late response! We've been tight up with some other projects and completely missed this. Yes, absolutely! We'd LOVE you to help create a Hindi version of the glossary.

**Comment by CathPag** [comment]
...btw, to get started, it'd be great if you could join one of our meetings (either the business value subcommittee or the glossary working group). To do that, please join the #marketing-business-value channel on the [CNCF Slack](https://lists.cncf.io/g/harbor-users/message/74) and ask to be added to the meeting invite. Looking forward to working on this with you!!

**Comment by edsoncelio** [comment]
Thanks @CathPag! for sure i'll join :D

**Comment by JasonMorgan** [comment]
@murillodigital I assigned you to see if there is anymore we need to do here or if you already have a plan for localization. Thanks!

**Comment by DouglasLopez** [comment]
Hello, guys, I want to participate in the Spanish translation please let me know how I can help

**Comment by CathPag** [comment]
That's great, @DouglasLopez! We are having our official localization kickoff meeting on Thursday during the Glossary Working Group meeting. Any chance you could join? You can find the invite on the[ CNCF calendar](https://www.cncf.io/calendar/).

**Comment by DouglasLopez** [comment]
Thanks I will be there

**Comment by sayantani11** [comment]
@CathPag Sorry I was also busy... And yes I will be there as well

**Comment by sayantani11** [comment]
@CathPag Sorry I was also busy... And yes I will be there as well

**Comment by CathPag** [comment]
@sayantani11, sorry we missed you. Please join the #glossary-localizations and #glossary-localization-hindi channel if you are still interested.

**Comment by sayantani11** [comment]
Okay @CathPag

**Comment by JasonMorgan** [comment]
OBE
