### ISSUE TITLE
Initiate Traditional Chinese Localization Team

### ISSUE THREAD

**Issue by pichuang** [cncf/glossary#1987]
# This issue is to initiate a new l10n Team

Please only use this template for submitting a new l10n team initiation requests. 

See https://github.com/cncf/glossary/blob/main/LOCALIZATION.md for basic requirements for a new l10n team.

---

### (1) The language and language code for l10n
Find localization's two-letter language code from [ISO 639-1 standard](https://www.loc.gov/standards/iso639-2/php/code_list.php).

For example, the two-letter code for Korean is `ko`.

 - Language name (ex: `Korean`): Traditional Chinese
 - Language two-letter code (ex: `ko`): zh-tw

### (2) List of volunteers
Name and GitHub Username for each l10n volunteer. Add `[A]` to make them approvers.

Ex: `- [A] Seokho Son (@seokho-son)`

- [A] Ader Fu (@ydFu)
- [A] Phil Huang (@pichuang)
- Cody Chen (@cdxvy30)
- Kent Lin (@kentlin520)
- Eagle Tseng (@tsengeagle)

---
### (Note) Next actions from maintainers

 - Create a new development branch for the l10n. (ex: `dev-ko`)
 - Update codeowners to add l10n contents approvers.
 - Add a new label for the language.

**Comment by kentlin520** [comment]
I have a new propose with  `dev-zh-TW` , for both showing the purpose in zh and identity with TW  mandarin .

Any suggestion or foreseeing warning is welcome.

**Comment by ydFu** [comment]
The additional information is as follows:

To add Traditional Chinese (`zh-tw`) as a language option for localization (l10n), we will use the language and language code. 
`zh` is the language code that refers to ISO-639, and `tw` is the country code that refers to ISO-3166.

For instance, [google/docsy](https://github.com/google/docsy/blob/main/i18n/zh-tw.toml) currently uses `zh-tw` as the language code for Traditional Chinese.

**Comment by seokho-son** [comment]
Things we need to check and decide for the following naming issue. :slightly_smiling_face:
(let's decide quickly and start actual contributions!)

**(To be added)**
[1] Team name
 - [1.1] Traditional Chinese Team
 - [1.2] Taiwan Team

[2] Slack channel name
 - [2.1] glossary-localization-traditional-chinese
 - [2.2] glossary-localization-taiwan

[3] Slack channel name
 - [3.1] glossary-localization-traditional-chinese
 - [3.2] glossary-localization-taiwan

[4] Language code & working directory:
 - zh-tw

[5] Dev branch
 - dev-tw

[6] Label
 - lang/tw

[7] URL Path
 - https://glossary.cncf.io/zh-tw/

[8] Language name in the language selection (the dropdown)
 - 繁體中文(Traditional Chinese)

**(To be changed)**
Language name in the language selection (the dropdown)
 - 中文(Chinese) --> 簡体中文(Simplified Chinese)
Note: We don't have to setup redirection for this change because the current 中文(Chinese) are using https://glossary.cncf.io/zh-ch/ already.

---
I guess we have a concensus on [4-8]
I hope to check which one is appropriate for [1-3].
[1.1] or [1.2] ?
[2.1] or [2.2] ?
[3.1] or [3.2] ?

Please share your idea, here or https://cloud-native.slack.com/archives/C02N2RGFXDF/p1683017705259579?thread_ts=1682521759.437899&cid=C02N2RGFXDF

**Comment by pichuang** [comment]
My preference is:

[1] Team name
- [1.1] Traditional Chinese Team
[2] Slack channel name
- [2.1] glossary-localization-traditional-chinese
[3] Slack channel name
- [3.1] glossary-localization-traditional-chinese

@ydFu @kentlin520 @cdxvy30 @tsengeagle Please share your feedback here or Slack if possible

**Comment by cdxvy30** [comment]
Agree with this decision.

**Comment by ydFu** [comment]
> My preference is:
> 
> [1] Team name
> - [1.1] Traditional Chinese Team

>  [2] Slack channel name
> * [2.1] glossary-localization-traditional-chinese

>   [3] Slack channel name
> * [3.1] glossary-localization-traditional-chinese
> 
> @ydFu @kentlin520 @cdxvy30 @tsengeagle Please share your feedback here or Slack if possible
> 

I also prefer the above setting.

**Comment by cdxvy30** [comment]
Also agree with this decision.

Phil Huang ***@***.***>於 2023年5月2日 週二，18:25寫道：

**Comment by tsengeagle** [comment]
Also agree with these

> My preference is:
> 
> * [1.1] Traditional Chinese Team
> * [2.1] glossary-localization-traditional-chinese
> * [3.1] glossary-localization-traditional-chinese
> 
> @ydFu @kentlin520 @cdxvy30 @tsengeagle Please share your feedback here or Slack if possible

**Comment by kentlin520** [comment]
Also agree with idea :

[1.1] Traditional Chinese Team
[2.1] glossary-localization-traditional-chinese
[3.1] glossary-localization-traditional-chinese

**Comment by seokho-son** [comment]
Ader Fu (@ydFu), Phil Huang (@pichuang), Cody Chen (@cdxvy30), Kent Lin (@kentlin520), Eagle Tseng (@tsengeagle) !
Thank you the initiation of Traditional Chinese Team !

Created dev branch and label for Traditional Chinese! You can use the branch now. 
- Development branch: `dev-tw` (https://github.com/cncf/glossary/tree/dev-tw)
- Issue/PR label: https://github.com/cncf/glossary/labels/lang%2Ftw (https://github.com/cncf/glossary/labels) 

Maintainers will create a Slack channel soon. (we are discussing if we should use #glossary-localization-zh-tw and update the other channels too)

- Next step: https://github.com/cncf/glossary/blob/main/LOCALIZATION.md
- Some references (related PRs/Issues): https://github.com/cncf/glossary/projects/2

To Traditional Chinese Team approver candidates Ader Fu (@ydFu), Phil Huang (@pichuang),
I am going to open a PR to add @ydFu @pichuang to Traditional Chinese contents approver (owner).
In the meantime, please check the following policy.
[Policies for localization approvers (to be confirmed by candidates) #723](https://github.com/cncf/glossary/discussions/723)

**Comment by seokho-son** [comment]
@pichuang @ydFu 
PTAL #2003 :)

**Comment by pichuang** [comment]
With @CathPag assistance, we have officially launched the Slack Channel [#glossary-localization-traditional-chinese](https://app.slack.com/huddle/T08PSQ7BQ/C055KERTNCX) . We welcome anyone who wishes to contribute to the Traditional Chinese to join this channel for discussion.

Both English and Mandarin languages are welcome.

https://app.slack.com/huddle/T08PSQ7BQ/C055KERTNCX
