### ISSUE TITLE
version control & gitops

### ISSUE THREAD

**Issue by MaryamTavakkoli** [cncf/glossary#2073]
#### Why this term needs to be updated? (briefly)
- Both terms exist in https://github.com/cncf/glossary/blob/main/content/en but those are not visible in the website https://glossary.cncf.io/
- I don't know the reason why it is not shown.

### 2. Checklist

- [X] I understand that maintainers will confirm if the term should be updated. (Please be patient)
- [ ] I want to work on this suggestion and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)".. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by jihoon-seo** [comment]
Hi @MaryamTavakkoli
After some discussion, maintainers agreed to deprecate the term 'Version Control', since the term not that 'cloud-native'.
For similar reason, the term 'GitOps' was added with `status: Feedback Appreciated` (which makes the term not visible in the website) and the state has never been changed.
If you think that the term 'GitOps' is indeed a cloud-native one, then please let us know and this issue could be the starting point of re-assessment of the term.

**Comment by MaryamTavakkoli** [comment]
Thanks for the. explanation @jihoon-seo,
Yes, at least I heard the term GitOps a lot in the KubeCon this year! So, I assume it might be an important one in the cloud-native area. It is also similar to DevOps and DevSecOps terms that are already part of the glossary. 

I also noticed there is an issue about simplifying the current definition https://github.com/cncf/glossary/issues/372
The current assignee has not been active for a long time, I can work on it if is needed.

**Comment by CathPag** [comment]
Can you please comment on the GitOps issue so I can assign it to you, @MaryamTavakkoli?

**Comment by CathPag** [comment]
I think this issue can be closed, so doing that now
