### ISSUE TITLE
[New term] `GitOps`

### ISSUE THREAD

**Issue by aakankshabhende** [cncf/glossary#2226]
#### What this term is about? (briefly)
- GitOps is a cloud-native practice for deploying software in which Git is used as a single source of truth for any deployment resources that happen in the system.

#### Why this term needs to be added? (briefly) 
- It is useful in situations when using version control to manage infrastructure and application deployment and is an important term to know.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)". (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by jihoon-seo** [comment]
We already have an explanation of the term 'GitOps': https://github.com/cncf/glossary/blob/main/content/en/gitops.md?plain=1
but it is not exposed on the website since the `status` is set to `Feedback Appreciated`, not `Completed`, which means that we think the term definition needs more enhancements.
There is an open PR that suggests the update of that term, so you can contribute by reviewing the PR.

Since there exist issues regarding 'GitOps' (#265, #2121), I am going to close this one.

Thank you again for your interest on this project!
