### ISSUE TITLE
add new term Automation

### ISSUE THREAD

**Issue by jgershater** [cncf/glossary#266]
### What it is
Automation automates manual procedures and static scripts

### Problem it addresses
Helps administrators and operators manage environments by automating previously manual operations.

### How it helps
Speeds up administration and configuration of environments

**Comment by Nawaz027** [comment]
Hey @jgershater , may I help with this term???

**Comment by jgershater** [comment]
> Hey @jgershater , may I help with this term???

of course!

**Comment by Nawaz027** [comment]
thanks. I am working on it.

**Comment by Alt-Shivam** [comment]
Hey, @JasonMorgan 
I would like to work on it.
Thanks

**Comment by manavsiddharthgupta** [comment]
can any one assign me

**Comment by CathPag** [comment]
Hey, sorry, I haven't been getting notifications for this issue. We have now a #glossary channel on the CNCF Slack. When you want to claim a term, please feel free to ping me and Jason in the channel to be sure we see it — thank you! 

I see @Alt-Shivam @manavsiddharthgupta and @Nawaz027 were interested in it. ...so, let's start from scratch. Who wants to take this term?

**Comment by mayank-cse** [comment]
@CathPag ma'am & @jgershater Sir
If this is not assigned yet, I would like to work on it.

**Comment by CathPag** [comment]
Done :)

**Comment by Alt-Shivam** [comment]
@mayank-cse 
Go for it. 👍

**Comment by mayank-cse** [comment]
thank you
I'm on it

**Comment by mayank-cse** [comment]
@CathPag would you like to suggest anything in the following definition
Automation is a term for technology applications where human input is minimized. When any process is set-up in a way which requires less or zero human intervention is known as automation.

TYPES OF AUTOMATION SYSTEMS

FIXED AUTOMATION Also referred to as hard automation, fixed automation systems carry out a single set of tasks without deviation. Because of its function, this type of system would typically be used for discrete mass production and continuous flow systems.
PROGRAMMABLE AUTOMATION As the names suggests, programmable automation runs through commands delivered by a computer program. This means that the resulting processes can vary widely with changing instructions given to the computer through a series of code.
FLEXIBLE AUTOMATION Also referred to as soft automation, this type of automation is utilized in computer-controlled flexible manufacturing systems and allows for a more flexible production.
INTEGRATED AUTOMATION Integrated automation involves the total automation of manufacturing plants as it is entirely handled by computers and control processes with minimal human involvement. Computers can design the necessary parts, test the designs, and fabricate the parts. Integrated automation, like flexible automation, is compatible with both batch process manufacturing and continuous process manufacturing.
Problem it addresses

Automation helps administrators and operators manage environments by automating previously manual operations.
How it helps

Automation speeds up administration and configuration of environments

**Comment by mayank-cse** [comment]
I have generated a pull request #322 
Kindly check it
Thank you
