### ISSUE TITLE
Use Github Actions to automate addition of labels for issues

### ISSUE THREAD

**Issue by avinashupadhya99** [cncf/glossary#337]
### Details (optional)

Instead of manually adding labels for the language based issues, use the Github action [`Naturalclar/issue-action`](https://github.com/marketplace/actions/issue-auto-labeling-and-assigning) to add labels based on the title of the issue.

**Comment by ShivamTyagi12345** [comment]
Have you raised this issue to work on it yourself @avinashupadhya99? If not.,I want to learn more about this .Please assign

**Comment by avinashupadhya99** [comment]
Please go ahead, one of the maintainers will be able to assign it to you. Ask on the #glossary channel on the CNCF slack.

**Comment by seokho-son** [comment]
I prefer [Labeler](https://github.com/marketplace/actions/labeler) since this Github Action can add labels based on File Path.

```
# Add 'label1' to any changes within 'example' folder or any subfolders
label1:
- example/**/*

# Add 'label2' to any file changes within 'example2' folder
label2: example2/*
```

Since we have many localization directories in `content/`, 
 - https://github.com/cncf/glossary/tree/main/content

It will be beneficial if we can add localization label automatically.
For instance,
 - add `lang/en` label if a PR includes changes for content/en/xx.md file
 - add `lang/ko` label if a PR includes changes for content/ko/xx.md file
 - add `lang/pt` label if a PR includes changes for content/pt/xx.md file
 - ..

What do you think of this idea ? @JasonMorgan

**Comment by ShivamTyagi12345** [comment]
> I prefer [Labeler](https://github.com/marketplace/actions/labeler) since this Github Action can add labels based on File Path.
> 
> ```
> # Add 'label1' to any changes within 'example' folder or any subfolders
> label1:
> - example/**/*
> 
> # Add 'label2' to any file changes within 'example2' folder
> label2: example2/*
> ```
> 
> Since we have many localization directories in `content/`,
> 
> * https://github.com/cncf/glossary/tree/main/content
> 
> It will be beneficial if we can add localization label automatically. For instance,
> 
> * add `lang/en` label if a PR includes changes for content/en/xx.md file
> * add `lang/ko` label if a PR includes changes for content/ko/xx.md file
> * add `lang/pt` label if a PR includes changes for content/pt/xx.md file
> * ..
> 
> What do you think of this idea ? @JasonMorgan

I find this helpful.I will try and implement this :)

**Comment by seokho-son** [comment]
@ShivamTyagi12345 Maintainers have a consensus on using [Labeler](https://github.com/marketplace/actions/labeler) :)

Please go ahead.
You can check the existing labels "lang/xx" in https://github.com/cncf/glossary/labels and corresponding directory is "content/xx/*"

Since there are many PRs from l10n teams, the priority for the configuration of [Labeler](https://github.com/marketplace/actions/labeler) seems high. :)

Please open a PR when you are ready.

**Comment by ShivamTyagi12345** [comment]
hey @seokho-son  can u please help me with this part 
<img width="542" alt="image" src="https://user-images.githubusercontent.com/60812924/153735987-e8a0cd37-c49a-4e0f-8b3d-a460f80f4168.png">
How do i add labels now

**Comment by seokho-son** [comment]
@ShivamTyagi12345 

> How do i add labels now

do you mean label matching rule ?

[lang/ar](https://github.com/cncf/glossary/labels/lang%2Far) : content/ar/*
[lang/bn](https://github.com/cncf/glossary/labels/lang%2Fbn) : content/bn/*
[lang/de](https://github.com/cncf/glossary/labels/lang%2Fde) : content/de/*
[lang/en](https://github.com/cncf/glossary/labels/lang%2Fen) : content/en/*
[lang/es](https://github.com/cncf/glossary/labels/lang%2Fes) : content/es/*
[lang/hi](https://github.com/cncf/glossary/labels/lang%2Fhi) : content/hi/*
[lang/it](https://github.com/cncf/glossary/labels/lang%2Fit) : content/if/*
[lang/ko](https://github.com/cncf/glossary/labels/lang%2Fko) : content/ko/*
[lang/pt](https://github.com/cncf/glossary/labels/lang%2Fpt) : content/**_pt-br_**/*

I expect like this ..

```
lang/ko:
- content/ko/*

lang/bn:
- content/bn/*

...

lang/pt:
- content/pt-br/*
```

**Comment by ShivamTyagi12345** [comment]
Yes. That's what I needed help with. Thanks
