### ISSUE TITLE
Document how another org can spin up their own glossary

### ISSUE THREAD

**Issue by caniszczyk** [cncf/glossary#426]
Hey @cjyabraham let's chat about how to do this, I've had requests from other projects that want their own glossary now and I think we should consider maybe creating a basic theme out of this site that folks can use.

**Comment by cjyabraham** [comment]
[Here is a WIP](https://github.com/cncf/glossary/blob/main/spin-new-glossary.md). Is this what you had in mind? Are there any teams out there that would be interested in trying this out?

**Comment by cjyabraham** [comment]
I've completed the first draft of [the instructions to modify the Glossary code for a new glossary](https://github.com/cncf/glossary/blob/main/spin-new-glossary.md). It's pretty lean but hopefully points people to all the things they need to do to start their own glossary site. If there is a team interested in doing this, it'd be good to connect with them so that we can work out any kinks in the instructions and elaborate as necessary.

**Comment by JasonMorgan** [comment]
@cjyabraham do we have a linked PR or should we be closing this out? It looks like your guide is already merged in.

**Comment by cjyabraham** [comment]
Yes, it's merged and this issue can be closed.
