### ISSUE TITLE
[Bug] Topic - "Stateless Apps" missing in the Search filter

### ISSUE THREAD

**Issue by verma-kunal** [cncf/glossary#670]
The topic of `Stateless Apps` is missing from the search filter! Therefore, not able to separately access & navigate to the term

https://user-images.githubusercontent.com/72245772/160981106-94f8cb89-241c-470b-ba0b-931604e62282.mov

**Comment by seokho-son** [comment]
@verma-kunal Thank you for the report!

it is because,

the status of `Stateless Apps` is `Feedback Appreciated`

> title: Stateless Apps
> status: Feedback Appreciated
> category: technology

If the document is not `completed` status, the document is not visible from the sidebar tree and search.

But, `Stateful Apps` doc includes the link to `Stateless Apps` so you could access to the document.

I am not sure why the status of `Stateless Apps` is still `Feedback Appreciated`.
I guess it is because the content is not mature enough to go live yet.

@CathPag 
I think we need to remove the link for `Stateless Apps` in  [`Stateful Apps`](https://glossary.cncf.io/stateful_apps/)

or change status of `Stateless Apps` doc to `completed`.

Please coordinate :)

**Comment by verma-kunal** [comment]
> it is because,
> 
> the status of `Stateless Apps` is `Feedback Appreciated`

Oh, got it! Thanks for clarifying @seokho-son

**Comment by verma-kunal** [comment]
> @CathPag I think we need to remove the link for `Stateless Apps` in [`Stateful Apps`](https://glossary.cncf.io/stateful_apps/)
> 
> or change status of `Stateless Apps` doc to `completed`.

+1

**Comment by CathPag** [comment]
I'm afraid we still haven't been able to get a mergeable definition. See conversation in [this PR](https://github.com/cncf/glossary/pull/430). It's a really tough nut to crack and Jason and I wanted to try to bring it over the finish line ourselves soon. We do need it to go with stateless apps. I'll go ahead and close this issue.
