### ISSUE TITLE
[hi] Localize `load_balancer` in `Hindi`

### ISSUE THREAD

**Issue by octonawish-akcodes** [cncf/glossary#779]
### Please describe why this term needs to be added

Localizing load balancer term in hindi.

**Comment by sumit-158** [comment]
can I work on this? @abh139 @Garima-Negi

**Comment by taniaduggal** [comment]
I want to work on this. Please assigned it to me @anubha-v-ardhan @Garima-Negi

**Comment by Garima-Negi** [comment]
@sumit-158 @octonawish-akcodes loadbalancer is not a term in the english glossary. hence, closing this issue

**Comment by Garima-Negi** [comment]
@jihoon-seo have a doubt regarding loadbalancer.md 
I don't see the term in [https://glossary.cncf.io/](https://glossary.cncf.io/ )
but if i look at the repository, file is present: [https://github.com/cncf/glossary/blob/main/content/en/load-balancer.md](https://github.com/cncf/glossary/blob/main/content/en/load-balancer.md)

I'll reopen this issue is we clarify. thanx!
