### ISSUE TITLE
[New term] Trunk based Development

### ISSUE THREAD

**Issue by prabin-acharya** [cncf/glossary#834]
#### What this term is about? (briefly)
- Trunk-based Development is a  development practice where developers merge small, frequent updates to a core “trunk” or main branch. 
#### Why this term needs to be added? (briefly) 
- Trunk-based Development is a popular development practice and helps achieve CI/CD.

### 2. Checklist

- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term. (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

**Comment by seokho-son** [comment]
Hi @prabin-acharya 
I am one of maintainers of this repository. 
In a maintainers' meeting, we decided not to include the term you suggested because the term is not highly (directly) related with cloud native technology and seems to a broad concept for development. If we include this term, we eventually need to include terms for other development practices which make the Glossary project cover too broad concepts.

Thank you for your interest for the Cloud Native Glossary. We will look forward your suggestions and contributions!
(cc @CathPag)
